---
panel_port: 2053

local_secrets_file: "{{ playbook_dir }}/../data/secrets/users.json"
local_keys_file: "{{ playbook_dir }}/../data/secrets/server_keys.json"
configs_output_dir: "{{ playbook_dir }}/../data/configs"
